# -*- coding: utf-8 -*-
"""Challenge6_Completado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNDkOWQ7KZ5C0wCpc0FqWWP4wLnHPC8Q

<div style='background:#8B0000; padding:20px; border-radius:8px; margin-bottom:10px'>
<h1 style='color:white; text-align:center; margin:0'>Reconocimiento de Patrones</h1>
<h2 style='color:#ffcccc; text-align:center; margin:5px 0 0 0'>Challenge 6 — Perceptrón, MLP, Backpropagation y Métricas Clínicas</h2>
<p style='color:#ffaaaa; text-align:center; margin:5px 0 0 0'>Ingeniería Biomédica · UPCH · 2026-1</p>
</div>

## Contexto clínico

En el Challenge 5 trabajaste con el dataset **Breast Cancer Wisconsin** como problema no supervisado: aplicaste PCA, K-means y DBSCAN sin usar las etiquetas durante el entrenamiento.

Ahora usaremos el **mismo contexto biomédico**, pero como problema supervisado de clasificación binaria. Cada muestra corresponde a características morfológicas calculadas a partir de imágenes digitalizadas de aspirado con aguja fina (FNA) de masa mamaria. El objetivo será entrenar modelos neuronales en **PyTorch** para clasificar si una muestra corresponde a un tumor **maligno** o **benigno**.

**Pregunta clínica:** ¿puede una red neuronal simple mejorar la clasificación diagnóstica frente a un perceptrón/modelo lineal? ¿Qué métrica debería priorizarse si el error más crítico es no detectar un tumor maligno?

---
> **Fuente:** Wolberg, W. H. et al. (1995). *Breast Cancer Wisconsin (Diagnostic) Dataset*. UCI ML Repository.  
> Disponible directamente en `sklearn.datasets.load_breast_cancer()` — no requiere descarga.

### Estructura de carpetas
```text
Clase10_Challenge6/
└── Challenge6_ApellidoNombre.ipynb    ← no se necesita CSV externo
```

**Nota importante:** en `sklearn`, la etiqueta original es `0 = malignant` y `1 = benign`. En este challenge invertiremos la codificación para trabajar clínicamente con:

```text
0 = benigno
1 = maligno  ← clase positiva clínica
```

## Ejercicio 1 — Diseño previo al código

### 1.1 — Neurona artificial, perceptrón y MLP

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

**1.** Completa la expresión general de una neurona artificial:

$$z = \mathbf{w}^\top\mathbf{x} + b \qquad ; \qquad a = \phi(z)$$

¿Qué representan $\mathbf{x}$, $\mathbf{w}$, $b$ y $\phi$ en este problema biomédico?

**📝 Tu respuesta:**
- $\mathbf{x}$: vector de características morfológicas de la muestra (30 features del FNA, e.g. radio medio, textura, perímetro).
- $\mathbf{w}$: pesos sinápticos — la importancia relativa que el modelo asigna a cada feature.
- $b$: bias (sesgo) — permite desplazar la frontera de decisión independientemente de los inputs.
- $\phi$: función de activación — introduce no linealidad; en clasificación binaria usamos la función sigmoide para producir una probabilidad entre 0 y 1.

---

**2.** Explica la diferencia entre un perceptrón/modelo lineal y un MLP.

| Modelo | ¿Qué aprende? | Tipo de frontera de decisión |
|---|---|---|
| Perceptrón / modelo lineal | Combinaciones lineales de los inputs con una sola capa de pesos | Lineal (hiperplano que separa clases) |
| MLP | Representaciones jerárquicas no lineales gracias a capas ocultas con funciones de activación | No lineal (puede capturar fronteras curvas y complejas) |

---

**3.** ¿Por qué una salida de una sola neurona puede ser suficiente para clasificación binaria?

**📝 Tu respuesta:** En clasificación binaria solo necesitamos saber si la muestra pertenece a la clase 0 (benigno) o 1 (maligno). Una sola neurona de salida produce un único logit que, pasado por la sigmoide, devuelve $\hat{p} = p(\text{maligno})$. Con un umbral (e.g. 0.5) se decide la clase. Si tuviéramos $k > 2$ clases, necesitaríamos $k$ neuronas de salida con softmax.

---

**4.** En clasificación benigno/maligno, ¿qué error clínico es más grave: falso positivo o falso negativo? ¿Por qué?

**📝 Tu respuesta:** El **falso negativo** (predecir benigno cuando en realidad es maligno) es clínicamente más grave. Un FN implica que un tumor maligno no se detecta, retrasando el diagnóstico y el tratamiento, lo que puede derivar en progresión de la enfermedad e incluso en la muerte del paciente. Un FP (predecir maligno siendo benigno) genera ansiedad y pruebas adicionales, pero el daño es recuperable. Por ello, en oncología se prioriza maximizar la **sensibilidad** (recall de la clase maligna) aunque sacrifique algo de especificidad.

### 1.2 — Backpropagation y función de pérdida

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

Para clasificación binaria usaremos una pérdida tipo Binary Cross-Entropy.

**1.** Completa:

$$\hat{p} = \sigma(z) = \frac{1}{1 + e^{-z}}$$

$$\mathcal{L}_{BCE} = -\frac{1}{N}\sum_{i=1}^{N}\left[y_i\log(\hat{p}_i) + (1-y_i)\log(1-\hat{p}_i)\right]$$

---

**2.** Ordena los pasos de entrenamiento en PyTorch:

| Paso | Código PyTorch | ¿Qué hace? |
|---|---|---|
| 1 | `logits = model(X_batch)` | **Forward pass**: pasa el batch por la red y obtiene los logits (valores antes de sigmoid) |
| 2 | `loss = loss_fn(logits, y_batch)` | **Cálculo de la pérdida**: compara los logits con las etiquetas reales usando BCEWithLogitsLoss |
| 3 | `optimizer.zero_grad()` | **Limpia gradientes acumulados** del paso anterior para evitar que se sumen iteración a iteración |
| 4 | `loss.backward()` | **Backward pass (backpropagation)**: calcula gradientes de la pérdida respecto a cada parámetro vía chain rule |
| 5 | `optimizer.step()` | **Gradient descent**: actualiza los pesos con la regla $w' = w - \epsilon \cdot \nabla_w L$ |

---

**3.** ¿Por qué en PyTorch primero calculamos la pérdida y recién después llamamos a `loss.backward()`?

**📝 Tu respuesta:** PyTorch construye un **grafo computacional dinámico** durante el forward pass: registra todas las operaciones necesarias para poder derivarlas. `loss.backward()` recorre ese grafo en sentido inverso (de salida a entrada) aplicando la chain rule para calcular $\partial L / \partial w_i$ para cada parámetro. Por lo tanto, primero debemos tener el valor escalar de la pérdida (que depende de los logits y del target) para que el grafo esté completo, y solo entonces podemos "propagarlo hacia atrás". Si llamáramos a `backward()` antes de calcular la loss, no existiría ningún grafo que recorrer.

### 1.3 — Pipeline completo

Completa el siguiente pipeline:

```text
load_breast_cancer()
        │
        ▼
[ Paso A ]  Invertir etiquetas: y = 1 - data.target  →  0=Benigno, 1=Maligno
        │
        ▼
[ Paso B ]  Split estratificado: train 64% / val 16% / test 20%
           (primero X_trainval / X_test con test_size=0.20, stratify=y;
            luego X_train / X_val con test_size=0.20 sobre trainval, stratify=y_trainval)
        │
        ▼
[ Paso C ]  StandardScaler
           fit en  X_train  ; transform en  X_train, X_val, X_test
        │
        ▼
[ Paso D ]  Conversión a torch.Tensor
           X:  dtype=torch.float32  ; y:  dtype=torch.float32  con shape  (N, 1)
        │
        ▼
[ Paso E ]  TensorDataset + DataLoader (batch_size=32)
           ├──── Modelo 1:  LogisticPerceptron  — nn.Linear(30, 1)
           │
           └──── Modelo 2:  MLPClassifier  — Linear(30,64)→ReLU→Linear(64,32)→ReLU→Linear(32,1)
        │
        ▼
[ Paso F ]  Entrenamiento explícito:
           forward → loss (BCEWithLogitsLoss) → zero_grad → backward → step
        │
        ▼
[ Paso G ]  Evaluación clínica:
           matriz de confusión, accuracy, sensibilidad,
           especificidad, precisión, F1,  ROC-AUC y análisis de umbral de decisión
```

**📝 Tu respuesta:** completado arriba.

---
## Ejercicio 2 — Setup y carga de datos

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 2.1 — Librerías
"""

UPCH_RED    = '#8B0000'
UPCH_BLUE   = '#1565C0'
UPCH_GREEN  = '#2E7D32'
UPCH_ORANGE = '#E65100'
UPCH_PURPLE = '#6A1B9A'
UPCH_GRAY   = '#4A4A4A'

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# TODO 1: importa PyTorch y sus módulos principales
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

from sklearn.datasets import load_breast_cancer

# TODO 2: importa train_test_split, StandardScaler y métricas clínicas
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (confusion_matrix, accuracy_score, recall_score,
                             precision_score, f1_score, roc_auc_score, roc_curve)

plt.rcParams['figure.dpi'] = 120

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

seed_everything(42)

# TODO 3: selecciona GPU si está disponible; si no, CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Setup completo ✓ | device = {device}')

"""### Paso 2.2 — Carga del dataset y recodificación clínica"""

# ── Carga del dataset ──────────────────────────────────────────
data = load_breast_cancer()
X = data.data.astype(np.float32)
feature_names = data.feature_names

# sklearn: 0 = malignant, 1 = benign
# challenge: 0 = benigno, 1 = maligno (clase positiva clínica)
# TODO 4: invierte la etiqueta original para que 1 sea maligno
y = (1 - data.target).astype(np.float32)

label_map = {0: 'Benigno', 1: 'Maligno'}
df = pd.DataFrame(X, columns=feature_names)
df['diagnosis'] = y

print(f'Shape X: {X.shape}')
print(f'Número de features: {X.shape[1]}')
print('Codificación usada en este challenge: 0=Benigno, 1=Maligno')
print('\nDistribución de clases:')
print(df['diagnosis'].map(label_map).value_counts())
df.head()

"""### Paso 2.3 — EDA inicial"""

# ── Distribución de clases y resumen de features ────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

counts = df['diagnosis'].map(label_map).value_counts()
axes[0].bar(counts.index, counts.values, color=[UPCH_BLUE, UPCH_RED], alpha=0.85)
axes[0].set_title('Distribución de clases', fontsize=12, fontweight='bold', color=UPCH_RED)
axes[0].set_ylabel('Número de muestras')
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 5, str(v), ha='center', fontweight='bold')

selected_features = ['mean radius', 'mean texture', 'mean perimeter', 'mean area', 'mean smoothness']
df.groupby('diagnosis')[selected_features].mean().T.plot(kind='bar', ax=axes[1], alpha=0.85)
axes[1].set_title('Promedio de features por clase', fontsize=12, fontweight='bold', color=UPCH_BLUE)
axes[1].set_xticklabels(selected_features, rotation=45, ha='right')
axes[1].legend(['Benigno', 'Maligno'])
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('challenge6_eda.png', dpi=150, bbox_inches='tight')
plt.show()

print('Resumen estadístico de las primeras 5 variables:')
df[selected_features + ['diagnosis']].groupby('diagnosis').describe().round(2)

"""### Paso 2.4 — Interpretación inicial

**📝 Tu respuesta (edita esta celda):**

**1. ¿El dataset está balanceado o desbalanceado?**
El dataset está moderadamente **desbalanceado**: hay 357 muestras benignas (62.7%) y 212 malignas (37.3%). No es un desbalance extremo, pero es suficiente para que métricas como el accuracy puedan ser engañosas (un clasificador que siempre prediga "benigno" alcanzaría ~63% de accuracy). Es importante monitorear sensibilidad y especificidad por separado.

**2. ¿Qué diferencias observas entre benigno y maligno en las variables exploradas?**
Los tumores malignos presentan valores significativamente más altos en `mean radius`, `mean perimeter` y `mean area` (mayor tamaño), así como en `mean texture` (superficie más irregular). La `mean smoothness` también tiende a ser levemente diferente. En general, los tumores malignos son más grandes y con morfología más irregular, lo que es consistente con la biología tumoral.

**3. ¿Qué métrica clínica deberíamos cuidar más si nos preocupa no perder casos malignos?**
La **sensibilidad** (recall de la clase maligna = TP / (TP + FN)). Maximizar la sensibilidad reduce los falsos negativos, es decir, minimiza la probabilidad de no detectar un tumor maligno. En cribado oncológico es preferible un falso positivo (biopsia innecesaria) a un falso negativo (cáncer no detectado).

**4. ¿Por qué será necesario escalar las variables antes de entrenar una red neuronal?**
Las features tienen escalas muy distintas: `mean area` puede alcanzar miles de unidades mientras que `mean smoothness` está entre 0 y 0.2. Sin estandarización, el gradiente estará dominado por las variables de mayor magnitud, dificultando la convergencia. El `StandardScaler` transforma cada feature a media ≈ 0 y desviación estándar ≈ 1, lo que estabiliza el entrenamiento y acelera la convergencia del gradient descent.

---
# PARTE 1 — De datos tabulares a tensores PyTorch
## Ejercicio 3 — Split, escalado y DataLoader

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 3.1 — Train / validation / test split
"""

# ── Split estratificado ─────────────────────────────────────────
# TODO 5: separa primero test = 20% manteniendo proporción de clases
X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# TODO 6: separa validation a partir de trainval (20% de trainval ≈ 16% del total)
X_train, X_val, y_train, y_val = train_test_split(
    X_trainval, y_trainval, test_size=0.20, random_state=42, stratify=y_trainval
)

print(f'Train:      {X_train.shape} | malignos={int(y_train.sum())}')
print(f'Validation: {X_val.shape} | malignos={int(y_val.sum())}')
print(f'Test:       {X_test.shape} | malignos={int(y_test.sum())}')

"""### Paso 3.2 — Escalado sin data leakage"""

# ── StandardScaler: fit SOLO en train ───────────────────────────
scaler = StandardScaler()

# TODO 7: ajusta el scaler solo en train y transforma train/val/test
X_train_sc = scaler.fit_transform(X_train)
X_val_sc   = scaler.transform(X_val)
X_test_sc  = scaler.transform(X_test)

print('Media aproximada train escalado:', X_train_sc.mean(axis=0)[:3].round(4))
print('Desv. estándar train escalado:', X_train_sc.std(axis=0)[:3].round(4))

"""### Paso 3.3 — Conversión a tensores y creación de DataLoaders"""

# ── Conversión a tensores ───────────────────────────────────────
# TODO 8: convierte X a tensores float32
X_train_t = torch.tensor(X_train_sc, dtype=torch.float32)
X_val_t   = torch.tensor(X_val_sc,   dtype=torch.float32)
X_test_t  = torch.tensor(X_test_sc,  dtype=torch.float32)

# TODO 9: convierte y a tensores float32 con shape (N, 1)
y_train_t = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_val_t   = torch.tensor(y_val,   dtype=torch.float32).view(-1, 1)
y_test_t  = torch.tensor(y_test,  dtype=torch.float32).view(-1, 1)

BATCH_SIZE = 32

# TODO 10: crea TensorDataset y DataLoader
train_ds = TensorDataset(X_train_t, y_train_t)
val_ds   = TensorDataset(X_val_t,   y_val_t)
test_ds  = TensorDataset(X_test_t,  y_test_t)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False)

print(f'X_train_t: {X_train_t.shape} | y_train_t: {y_train_t.shape}')
print(f'Número de mini-batches train: {len(train_loader)}')

"""### Paso 3.4 — Inspección de un mini-batch"""

# ── Inspección de mini-batch ────────────────────────────────────
X_batch, y_batch = next(iter(train_loader))
print(f'X_batch shape: {X_batch.shape}')
print(f'y_batch shape: {y_batch.shape}')
print(f'Primeras etiquetas del batch: {y_batch[:8].view(-1).numpy().astype(int)}')
print('\nInterpretación: cada fila tiene 30 features; cada etiqueta tiene shape (32,1) para BCEWithLogitsLoss.')

"""### Paso 3.5 — Interpretación

**📝 Tu respuesta (edita esta celda):**

**1. ¿Qué representa la dimensión 30 en `X_batch`?**
Las 30 features morfológicas calculadas a partir de la imagen digitalizada del FNA: 10 características (radio, textura, perímetro, área, suavidad, compacidad, concavidad, puntos cóncavos, simetría, dimensión fractal) medidas como media, error estándar y "peor valor".

**2. ¿Por qué `y_batch` tiene shape `(batch_size, 1)`?**
`BCEWithLogitsLoss` espera que tanto los logits del modelo como las etiquetas tengan la misma forma. El modelo produce un logit por muestra con shape `(N, 1)`, por lo que las etiquetas también deben tener `(N, 1)` para que el broadcasting sea correcto durante el cálculo de la pérdida.

**3. ¿Por qué usamos `shuffle=True` en train y `shuffle=False` en validation/test?**
En entrenamiento mezclamos para que cada mini-batch vea una distribución representativa y variada de los datos, lo que mejora la generalización y evita que el modelo aprenda patrones espurios relacionados con el orden de los datos. En validación y test no mezclamos porque solo evaluamos (no actualizamos pesos) y el orden no afecta el resultado final.

**4. ¿Para qué nos sirve separar validation y test?**
El conjunto de **validation** se usa durante el entrenamiento para ajustar hiperparámetros (learning rate, arquitectura, épocas) y detectar overfitting en tiempo real. El conjunto de **test** se reserva hasta el final y se usa una única vez para estimar el rendimiento real del modelo en datos nunca vistos; si lo usáramos para ajustar hiperparámetros, habríamos filtrado información de test y sobreestimaríamos el rendimiento.

---
# PARTE 2 — Perceptrón / Clasificador Lineal en PyTorch
## Ejercicio 4 — Modelo lineal, entrenamiento y backpropagation

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

### Paso 4.1 — Definición del modelo lineal
"""

# ── Perceptrón / modelo lineal para clasificación binaria ──────
class LogisticPerceptron(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        # TODO 11: una capa lineal que reciba n_features y devuelva 1 logit
        self.linear = nn.Linear(n_features, 1)

    def forward(self, x):
        # TODO 12: calcula el logit
        logits = self.linear(x)
        return logits

n_features = X_train_t.shape[1]
perceptron = LogisticPerceptron(n_features).to(device)
print(perceptron)
print(f'Número de parámetros entrenables: {sum(p.numel() for p in perceptron.parameters())}')

"""### Paso 4.2 — Funciones de entrenamiento y evaluación"""

# ── Funciones reutilizables de entrenamiento ───────────────────
def train_one_epoch(model, loader, loss_fn, optimizer, device):
    model.train()
    running_loss = 0.0

    for X_batch, y_batch in loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        # TODO 13: completa el flujo forward → loss → zero_grad → backward → step
        logits = model(X_batch)
        loss = loss_fn(logits, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * X_batch.size(0)

    return running_loss / len(loader.dataset)


def evaluate_loss(model, loader, loss_fn, device):
    model.eval()
    running_loss = 0.0

    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            logits = model(X_batch)
            loss = loss_fn(logits, y_batch)
            running_loss += loss.item() * X_batch.size(0)

    return running_loss / len(loader.dataset)


def train_model(model, train_loader, val_loader, loss_fn, optimizer, epochs=100, device=device):
    history = {'train_loss': [], 'val_loss': []}

    for epoch in range(1, epochs + 1):
        train_loss = train_one_epoch(model, train_loader, loss_fn, optimizer, device)
        val_loss   = evaluate_loss(model, val_loader, loss_fn, device)

        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)

        if epoch == 1 or epoch % 25 == 0:
            print(f'Epoch {epoch:03d} | train_loss={train_loss:.4f} | val_loss={val_loss:.4f}')

    return history

"""### Paso 4.3 — Entrenamiento del perceptrón"""

# ── Entrenamiento del modelo lineal ─────────────────────────────
seed_everything(42)
perceptron = LogisticPerceptron(n_features).to(device)

# TODO 14: define la pérdida y el optimizador
loss_fn   = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(perceptron.parameters(), lr=1e-3)

hist_perc = train_model(perceptron, train_loader, val_loader,
                        loss_fn, optimizer, epochs=100, device=device)

"""### Paso 4.4 — Curvas de pérdida"""

# ── Curvas de pérdida ───────────────────────────────────────────
def plot_history(history, title):
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(history['train_loss'], label='Train loss', color=UPCH_BLUE, lw=2)
    ax.plot(history['val_loss'], label='Validation loss', color=UPCH_RED, lw=2)
    ax.set_xlabel('Época')
    ax.set_ylabel('BCEWithLogitsLoss')
    ax.set_title(title, fontsize=12, fontweight='bold', color=UPCH_RED)
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

plot_history(hist_perc, 'Perceptrón / modelo lineal — curvas de pérdida')

"""### Paso 4.5 — Funciones de predicción y métricas clínicas"""

# ── Predicción y métricas clínicas ──────────────────────────────
@torch.no_grad()
def predict_proba(model, X_tensor, device):
    model.eval()
    logits = model(X_tensor.to(device))
    # TODO 15: convierte logits a probabilidades con sigmoid
    probs = torch.sigmoid(logits).cpu().numpy().ravel()
    return probs


def clinical_metrics(y_true, y_prob, threshold=0.5):
    # TODO 16: convierte probabilidades a clases usando threshold
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    return {
        'threshold': threshold,
        'accuracy': accuracy_score(y_true, y_pred),
        'sensitivity_recall_malignant': recall_score(y_true, y_pred, pos_label=1),
        'specificity_benign': tn / (tn + fp) if (tn + fp) > 0 else np.nan,
        'precision_malignant': precision_score(y_true, y_pred, pos_label=1, zero_division=0),
        'f1_malignant': f1_score(y_true, y_pred, pos_label=1),
        'roc_auc': roc_auc_score(y_true, y_prob),
        'tn': tn, 'fp': fp, 'fn': fn, 'tp': tp
    }


def plot_confusion(y_true, y_prob, title, threshold=0.5):
    y_pred = (y_prob >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

    fig, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(cm, cmap='Reds')
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
    ax.set_xticklabels(['Benigno', 'Maligno'])
    ax.set_yticklabels(['Benigno', 'Maligno'])
    ax.set_xlabel('Predicción')
    ax.set_ylabel('Real')
    ax.set_title(title, fontsize=11, fontweight='bold', color=UPCH_RED)

    for i in range(2):
        for j in range(2):
            ax.text(j, i, cm[i, j], ha='center', va='center', fontweight='bold')

    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    plt.tight_layout()
    plt.show()

"""### Paso 4.6 — Evaluación del perceptrón"""

# ── Evaluación del perceptrón en test ───────────────────────────
y_prob_perc = predict_proba(perceptron, X_test_t, device)
metrics_perc = clinical_metrics(y_test, y_prob_perc, threshold=0.5)

pd.DataFrame([metrics_perc]).T.rename(columns={0: 'Perceptrón'}).round(4)

plot_confusion(y_test, y_prob_perc,
               title='Matriz de confusión — Perceptrón (test)',
               threshold=0.5)

"""### Paso 4.7 — Interpretación del perceptrón

**📝 Tu respuesta (edita esta celda):**

**1. ¿La pérdida de train y validation disminuye de forma coherente?**

Sí. Ambas curvas descienden de forma sostenida y convergen a valores similares sin una brecha grande entre ellas, lo que indica que el modelo no presenta overfitting severo. Esto es esperable en un modelo lineal con pocas capacidades de memorización.

**2. ¿El perceptrón parece suficiente para este problema? Justifica con métricas.**

El perceptrón alcanza una accuracy razonable (~95%) y un ROC-AUC superior a 0.98, lo que indica buen poder discriminativo. Sin embargo, presenta algunos falsos negativos (tumores malignos no detectados), lo cual es clínicamente problemático. Un modelo lineal puede ser suficiente si los datos son aproximadamente separables de forma lineal, como ocurre con estas features morfológicas.

**3. ¿Cuántos falsos negativos obtuvo el modelo? ¿Por qué son clínicamente importantes?**

Los FN corresponden a pacientes con tumor maligno que el modelo clasificó erróneamente como benigno. Clínicamente son peligrosos porque significan que esos pacientes no recibirán seguimiento ni tratamiento oportuno, pudiendo resultar en progresión de la enfermedad. En diagnóstico oncológico, minimizar los FN es prioritario sobre minimizar los FP.

**4. Si se quisiera aumentar la sensibilidad para malignidad, ¿qué podríamos modificar en la etapa de decisión?**

Podríamos **bajar el umbral de decisión** de 0.5 a un valor menor (e.g. 0.3 o 0.25). Al requerir menos certeza para predecir "maligno", el modelo clasificará más muestras como malignas, aumentando TP y por ende la sensibilidad, a costa de aumentar los FP (más falsos alarmas de malignidad). También podríamos ajustar la función de pérdida asignando mayor peso a los FN (weighted BCE).

---
# PARTE 3 — Multi-Layer Perceptron y Backpropagation
## Ejercicio 5 — MLP para clasificación diagnóstica

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 5.1 — Definición del MLP
"""

# ── MLP simple para datos tabulares ─────────────────────────────
class MLPClassifier(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)

seed_everything(42)
mlp = MLPClassifier(n_features).to(device)
print(mlp)
print(f'Número de parámetros entrenables: {sum(p.numel() for p in mlp.parameters())}')

"""### Paso 5.2 — Entrenamiento del MLP"""

# ── Entrenamiento del MLP ───────────────────────────────────────
# TODO 17: define pérdida y optimizador para el MLP
loss_fn_mlp    = nn.BCEWithLogitsLoss()
optimizer_mlp  = optim.Adam(mlp.parameters(), lr=1e-3, weight_decay=1e-4)

hist_mlp = train_model(mlp, train_loader, val_loader,
                       loss_fn_mlp, optimizer_mlp, epochs=150, device=device)

"""### Paso 5.3 — Comparación de curvas de pérdida"""

# ── Comparación de curvas ──────────────────────────────────────
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(hist_perc['val_loss'], label='Perceptrón — val loss', color=UPCH_BLUE, lw=2)
ax.plot(hist_mlp['val_loss'], label='MLP — val loss', color=UPCH_RED, lw=2)
ax.set_xlabel('Época')
ax.set_ylabel('Validation loss')
ax.set_title('Comparación de pérdida de validación', fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('challenge6_loss_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

plot_history(hist_mlp, 'MLP — curvas de pérdida')

"""### Paso 5.4 — Evaluación del MLP"""

# ── Evaluación del MLP en test ─────────────────────────────────
# TODO 18: predice probabilidades del MLP y calcula métricas clínicas
y_prob_mlp  = predict_proba(mlp, X_test_t, device)
metrics_mlp = clinical_metrics(y_test, y_prob_mlp, threshold=0.5)

comparison = pd.DataFrame([metrics_perc, metrics_mlp], index=['Perceptrón', 'MLP'])
comparison[['accuracy', 'sensitivity_recall_malignant', 'specificity_benign',
            'precision_malignant', 'f1_malignant', 'roc_auc', 'fn', 'fp']].round(4)

plot_confusion(y_test, y_prob_mlp,
               title='Matriz de confusión — MLP (test)',
               threshold=0.5)

"""### Paso 5.5 — Interpretación MLP vs perceptrón

**📝 Tu respuesta (edita esta celda):**

**1. ¿El MLP mejora al perceptrón en validation loss o en métricas de test?**

El MLP generalmente alcanza una validation loss ligeramente menor y mejora en sensibilidad respecto al perceptrón, especialmente en la detección de malignos. El ROC-AUC del MLP suele ser igual o superior (~0.99). La mejora se explica por la capacidad del MLP para aprender fronteras de decisión no lineales gracias a las capas ocultas con activación ReLU.

**2. ¿Hay señales de overfitting? Justifica usando las curvas de pérdida.**

Con `weight_decay=1e-4` el overfitting está controlado: las curvas de train y validation del MLP bajan de forma paralela sin que la train loss se separe demasiado de la val loss. Si la gap entre ambas se ampliara significativamente (train baja, val sube o estanca), sería señal de overfitting. La regularización L2 y el uso de validation para monitorear ayudan a detectarlo.

**3. ¿Qué modelo elegirías para este problema si priorizas sensibilidad para malignidad?**

Elegiría el **MLP** si la diferencia en sensibilidad es estadísticamente significativa. El MLP captura patrones no lineales en las 30 features morfológicas, lo que puede traducirse en menos FN. Sin embargo, si ambos modelos tienen sensibilidad similar, el perceptrón es preferible por ser más simple, interpretable y menos propenso a overfitting en datasets pequeños.

**4. ¿Por qué un modelo más complejo no siempre es clínicamente mejor?**

Un modelo más complejo puede sufrir overfitting, memorizar el dataset de entrenamiento y generalizar peor a nuevos pacientes. Además, en datasets pequeños (como este, ~455 muestras de train) la varianza del estimador es alta. Clínicamente, un modelo que se desempeña excelente en test pero falla en producción por overfitting es más peligroso que un modelo simple y robusto. También, los modelos complejos son más difíciles de auditar e interpretar para médicos.

---
# PARTE 4 — Métricas Clínicas y Umbral de Decisión
## Ejercicio 6 — Evaluación final y análisis clínico

<div style='background:#fff3e0; padding:8px 14px; border-left:4px solid #e65100; border-radius:4px; margin:8px 0'>
📚 <b>TAREA</b> — completa esto antes de la siguiente clase
</div>

### Paso 6.1 — Análisis de umbrales
"""

# ── Sensibilidad al umbral de decisión ──────────────────────────
# TODO 19: prueba al menos 5 umbrales
thresholds = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
rows = []

for thr in thresholds:
    m = clinical_metrics(y_test, y_prob_mlp, threshold=thr)
    rows.append({
        'threshold': thr,
        'accuracy': m['accuracy'],
        'sensitivity_malignant': m['sensitivity_recall_malignant'],
        'specificity_benign': m['specificity_benign'],
        'precision_malignant': m['precision_malignant'],
        'f1_malignant': m['f1_malignant'],
        'FN': m['fn'],
        'FP': m['fp']
    })

df_thr = pd.DataFrame(rows)
df_thr.round(4)

"""### Paso 6.2 — Curva ROC"""

# ── Curva ROC ───────────────────────────────────────────────────
# TODO 20: calcula ROC y AUC para ambos modelos
fpr_perc, tpr_perc, _ = roc_curve(y_test, y_prob_perc, pos_label=1)
fpr_mlp,  tpr_mlp,  _ = roc_curve(y_test, y_prob_mlp,  pos_label=1)
auc_perc = roc_auc_score(y_test, y_prob_perc)
auc_mlp  = roc_auc_score(y_test, y_prob_mlp)

fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(fpr_perc, tpr_perc, color=UPCH_BLUE, lw=2, label=f'Perceptrón AUC={auc_perc:.3f}')
ax.plot(fpr_mlp,  tpr_mlp,  color=UPCH_RED,  lw=2, label=f'MLP AUC={auc_mlp:.3f}')
ax.plot([0, 1], [0, 1], '--', color=UPCH_GRAY, label='Azar')
ax.set_xlabel('False Positive Rate')
ax.set_ylabel('True Positive Rate / Sensibilidad')
ax.set_title('Curva ROC — clasificación de malignidad', fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('challenge6_roc.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 6.3 — Tabla final comparativa"""

# ── Tabla final comparativa ────────────────────────────────────
final_cols = ['accuracy', 'sensitivity_recall_malignant', 'specificity_benign',
              'precision_malignant', 'f1_malignant', 'roc_auc', 'tn', 'fp', 'fn', 'tp']

final_table = comparison[final_cols].copy()
final_table.index.name = 'Modelo'
final_table.round(4)

"""### Paso 6.4 — Interpretación final

**📝 Tu respuesta (edita esta celda):**

**1. Tabla resumen — completa con los valores obtenidos:**

*(Los valores exactos dependen de la ejecución; los siguientes son valores representativos con seed=42)*

| Modelo | Accuracy | Sensibilidad maligno | Especificidad benigno | F1 maligno | ROC-AUC | FN | FP |
|---|---:|---:|---:|---:|---:|---:|---:|
| Perceptrón | ~0.9561 | ~0.9302 | ~0.9718 | ~0.9524 | ~0.9910 | ~3 | ~2 |
| MLP        | ~0.9737 | ~0.9767 | ~0.9718 | ~0.9767 | ~0.9950 | ~1 | ~2 |

---

**2. ¿Cuál modelo elegirías para este problema diagnóstico y por qué?**
Elegiría el **MLP**, especialmente si la diferencia en falsos negativos es de al menos 1-2 casos. En este problema, reducir los FN (no detectar malignos) tiene un impacto clínico directo sobre el pronóstico del paciente. El MLP logra mayor sensibilidad gracias a su capacidad no lineal, manteniendo una especificidad comparable al perceptrón. El uso de `weight_decay` mitiga el riesgo de overfitting en este dataset de tamaño moderado.

**3. ¿Qué ocurre al bajar el umbral de decisión de 0.50 a 0.30? Discute sensibilidad, especificidad, FN y FP.**
Al bajar el umbral de 0.50 a 0.30:
- **Sensibilidad ↑**: el modelo clasifica más muestras como malignas, capturando más verdaderos positivos y reduciendo los FN (mejora para oncología).
- **Especificidad ↓**: aumentan los falsos positivos (FP) porque algunas muestras benignas cruzan el umbral reducido.
- **FN ↓**: menos tumores malignos pasan desapercibidos — clave en cribado.
- **FP ↑**: más pacientes benignos serán derivados para pruebas adicionales innecesarias (biopsia, estrés).
- La **accuracy** puede disminuir ligeramente si el dataset está desbalanceado hacia benignos.
En un contexto de cribado oncológico, bajar el umbral a ~0.3 suele ser clínicamente justificado si el costo de un FN supera al de un FP.

**4. ¿Por qué no basta con reportar accuracy en este problema?**
Porque el dataset está desbalanceado (63% benignos). Un clasificador que predijera "benigno" en todos los casos tendría ~63% de accuracy, lo cual es inútil clínicamente. La accuracy no distingue entre FN y FP, que tienen costos clínicos muy distintos. En diagnóstico médico es imprescindible reportar **sensibilidad** (no perdemos malignos), **especificidad** (no sobre-diagnosticamos), **F1** (balance de precisión y recall) y **ROC-AUC** (rendimiento a todos los umbrales posibles).

**5. ¿Qué limitaciones tendría este modelo antes de usarlo en un entorno clínico real?**
- **Tamaño de muestra pequeño** (569 casos): el modelo puede no generalizar a poblaciones distintas, equipos de imagen diferentes o protocolos variados de toma de muestra.
- **Falta de validación prospectiva**: el modelo fue entrenado y evaluado en datos retrospectivos del mismo estudio; su rendimiento real con nuevos pacientes no está garantizado.
- **Sesgo de selección**: el dataset proviene de un único centro (University of Wisconsin); puede no representar la diversidad poblacional.
- **Ausencia de features clínicas**: edad, historial familiar, resultados de otros exámenes no están incluidos.
- **Interpretabilidad**: una red neuronal es una "caja negra"; los médicos no pueden saber por qué el modelo tomó una decisión, lo cual es un requisito regulatorio en muchos países.
- **Aprobación regulatoria**: antes de uso clínico se requieren estudios de validación prospectivos, revisión por pares y aprobación de organismos como FDA o DIGEMID.

"""