# -*- coding: utf-8 -*-
"""Clase4_Challenge3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aHoBsaxUAa8PBAaOdarEnbjkMxNn6-a

<div style='background:#8B0000; padding:20px; border-radius:8px; margin-bottom:10px'>
<h1 style='color:white; text-align:center; margin:0'>Reconocimiento de Patrones</h1>
<h2 style='color:#ffcccc; text-align:center; margin:5px 0 0 0'>Challenge 3 — Overfitting, Regularización y SVM</h2>
<p style='color:#ffaaaa; text-align:center; margin:5px 0 0 0'>Ingeniería Biomédica · UPCH · 2026-1</p>
</div>

## Contexto clínico

Se te proporcionan dos datasets biomédicos independientes:

1. **EMG Gesture Classification** — features estadísticas de electromiografía de superficie (sEMG) registradas durante dos gestos activos de la mano. El dataset original tiene 3 clases (0=reposo, 1=pulgar abajo, 2=pulgar arriba); trabajaremos solo con **clases 1 y 2** — el problema clínicamente relevante: **¿el usuario intenta cerrar o abrir la mano?** Contexto: **control de prótesis mioeléctrica**.
2. **Brain Tumor MRI** — imágenes de resonancia magnética cerebral: **Tumor vs No tumor**. Pipeline: flatten → PCA → SVM.

---

### Datasets necesarios

| Datos | Fuente | Extensión |
|---|---|---|
| EMG Gesture Classification | [Kaggle](https://www.kaggle.com/datasets/birdy654/emg-gesture-classification-thumbs-up-and-down) | `.csv` |
| Brain Tumor MRI | [Kaggle](https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset) | `.jpg` |

```
Clase4_Challenge/
├── Challenge3_ApellidoNombre.ipynb
├── emg_gestures.csv
└── brain_tumor/
    ├── Training/
    │   ├── notumor/
    │   └── tumor/   (glioma + meningioma + pituitary)
    └── Testing/
        ├── notumor/
        └── tumor/
```

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

---
## Ejercicio 1 — Diseño previo al código (conceptual)

> **Antes de escribir una línea de código**, razona sobre el problema.

### 1.1 — Diagnóstico esperado

Responde antes de ver los datos:

1. La señal EMG de un músculo tiene patrones de amplitud y frecuencia distintos según el gesto. ¿Esperas que SVM Lineal o RBF funcione mejor para clasificar pulgar abajo vs pulgar arriba? ¿Por qué?
2. ¿Por qué es necesario PCA antes de SVM en imágenes MRI? ¿Qué pasaría si aplicaras SVM directamente sobre los 22 500 píxeles?
3. En una prótesis mioeléctrica, ¿qué error es más problemático: clasificar mal el gesto (FP) o no detectarlo (FN)? ¿Cambia la respuesta si lo comparas con el diagnóstico de tumor cerebral?

**📝 Tu respuesta (edita esta celda):**
1. Se espera que **SVM RBF** funcione mejor para EMG. Las features estadísticas extraídas de la señal sEMG describen patrones musculares que no se separan linealmente. El kernel RBF puede capturar esa complejidad sin necesidad de definirla explícitamente.
2. PCA es necesario antes de SVM porque cada imagen genera un vector de **22 500 features**. Con ese número de dimensiones el entrenamiento de SVM es computacionalmente inviable y el modelo overfittearía con facilidad. Además, elimina redundancia de píxeles vecinos conservando las direcciones de máxima varianza.
3. Para una **prótesis mioeléctrica**, un FP es más crítico porque puede causar un movimiento no deseado y peligroso. Para el **diagnóstico de tumor**, el FN es mucho más grave porque un paciente enfermo quedaría sin tratamiento; en screening se prioriza maximizar el recall (sensibilidad) aceptando más FP.

### 1.2 — Pipeline completo

Completa el pipeline para cada dataset:

```
emg_gestures.csv
    │
    ▼
[ Paso A ] _______________  ← ¿Qué haces primero? (antes del split)
    │
    ▼
[ Paso B ] _______________  ← ¿Cuándo haces el split? ¿Por qué aquí?
    │
    ▼
[ Paso C ] _______________  ← ¿Qué preprocesamiento? ¿Con qué datos?
    │
    ▼
[ Paso D ] _______________  ← ¿Cómo eliges C sin tocar el test?
    │
    ▼
[ Paso E ] _______________  ← ¿Cuándo y cómo evalúas en test?

Brain Tumor MRI
    │
    ▼
[ Paso A ] flatten + _______________
    │
    ▼
[ Paso B ] _______________  ← ¿Por qué PCA aquí y no antes del split?
    │
    ▼
[ Paso C ] _______________
```

**📝 Tu respuesta (edita esta celda):**
- EMG: [Paso A] Cargar el CSV, explorar y recodificar a 0/1. [Paso B] Split 80/20 estratificado antes de preprocesar para evitar data leakage. [Paso C] StandardScaler ajustado SOLO sobre train. [Paso D] Barrido de C usando cross_val_score (CV-5) sobre train. [Paso E] Con el C óptimo, entreno final sobre todo train y evalúo en test UNA SOLA VEZ.

- MRI: [Paso A] flatten + StandardScaler (fit solo en train). [Paso B] PCA (fit solo en train) porque las componentes no deben contaminarse con info del test. [Paso C] SVM-RBF sobre el espacio reducido con C seleccionado por CV.

# Cambio por uso  de libreria Kagglehub

En este caso usaremos la libreria de kaggle para poder descargar y guardar en memoria los datos. Con este paso evitaremos descargar y cargar de manera local los datos
"""

!pip install kagglehub

# ── Descarga de datasets con kagglehub ─────────────────────────────────────
import kagglehub
from pathlib import Path

"""## Carga de los datasets"""

# Dataset 1: EMG Gesture Classification
emg_dl_path = kagglehub.dataset_download('birdy654/emg-gesture-classification-thumbs-up-and-down')
print('Path EMG dataset:', emg_dl_path)

# Dataset 2: Brain Tumor MRI
mri_dl_path = kagglehub.dataset_download('masoudnickparvar/brain-tumor-mri-dataset')
print('Path MRI dataset:', mri_dl_path)

# Localizar el CSV de EMG (puede estar en subdirectorio)
emg_path = Path(emg_dl_path)
csv_candidates = list(emg_path.glob('**/*.csv'))
EMG_CSV = csv_candidates[0]
print(f'CSV EMG encontrado: {EMG_CSV}')

# Ruta raíz del dataset MRI
DATA_DIR_MRI = Path(mri_dl_path)
print(f'Carpeta MRI: {DATA_DIR_MRI}')

# ── Conexión con Google Drive ──────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

"""---
## Ejercicio 2 — Setup

"""

UPCH_RED   = '#8B0000'
UPCH_BLUE  = '#1565C0'
UPCH_GREEN = '#2E7D32'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import warnings
warnings.filterwarnings('ignore')

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import (train_test_split, learning_curve,
                                      StratifiedKFold, cross_val_score)
from sklearn.decomposition import PCA
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, ConfusionMatrixDisplay,
                              recall_score, precision_score, f1_score)

plt.rcParams['figure.dpi'] = 120
print('Setup completo ✓')

"""---
# PARTE 1 — Señal EMG: Control de Prótesis Mioeléctrica

## Ejercicio 3 — Carga, filtrado y EDA

El dataset contiene features estadísticas de sEMG con 3 clases originales:

| Clase | Gesto | Aplicación |
|---|---|---|
| 0 | Reposo (relax) | Estado neutro |
| 1 | Pulgar abajo | Apertura de mano |
| 2 | Pulgar arriba | Cierre de mano |

> Trabajamos con **clases 1 y 2** — el problema activo de la prótesis: ¿abrir o cerrar la mano?

### Paso 3.1 — Carga, inspección y filtrado

"""

df_raw = pd.read_csv(EMG_CSV)

print(f'Shape original: {df_raw.shape}')
print(f'\nDistribucion original de clases:')
TARGET = df_raw.columns[-1]
print(df_raw[TARGET].value_counts().sort_index())
df_raw.head()

# --- COMPLETA EL CÓDIGO ---
# TODO: filtra el dataframe conservando SOLO las filas donde TARGET == 1 o TARGET == 2
# Pista: usa isin()
df = df_raw[df_raw[TARGET].isin([1, 2])].copy()

# Recodificar: clase 1 → 0 (pulgar abajo), clase 2 → 1 (pulgar arriba)
# Esto convierte el problema a binario 0/1 para SVM
df = df.copy()
df[TARGET] = df[TARGET].map({1.0: 0, 2.0: 1})

print(f'Shape tras filtrado: {df.shape}')
print(f'\nClases tras recodificacion:')
print(df[TARGET].value_counts().sort_index())
print('  0 = Pulgar abajo  |  1 = Pulgar arriba')

"""### Paso 3.2 — EDA: distribución de features por gesto
> ¿Qué features tienen distribuciones más distintas entre pulgar abajo y arriba? Esas serán las más discriminativas para SVM.

"""

features_num = df.drop(columns=[TARGET]).columns[:6].tolist()

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
axes = axes.flatten()

for i, feat in enumerate(features_num):
    ax = axes[i]
    # --- COMPLETA EL CÓDIGO ---
    for clase, color, label in [(0, UPCH_BLUE, 'Pulgar abajo (0)'),
                                  (1, UPCH_RED,  'Pulgar arriba (1)')]:
        vals = df[df[TARGET] == clase][feat].values
        ax.hist(vals, bins=40, density=True, alpha=0.6, color=color, label=label)
        ax.axvline(vals.mean(), color=color, lw=2, ls='--')
    ax.set_title(feat, fontsize=9, fontweight='bold')
    ax.legend(fontsize=7)

plt.suptitle('EDA — Features EMG: Pulgar abajo vs Pulgar arriba',
             fontsize=12, fontweight='bold', color=UPCH_RED, y=1.02)
plt.tight_layout()
plt.savefig('eda_emg.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## Ejercicio 4 — Preprocesamiento EMG

### Paso 4.1 — Split estratificado y escalado z-score

> **Regla:** separar primero, preprocesar después. El `StandardScaler` se ajusta **solo sobre train**.

"""

X_raw = df.drop(columns=[TARGET]).values
y_raw = df[TARGET].values.astype(int)   # 0 = pulgar abajo, 1 = pulgar arriba

# --- COMPLETA EL CÓDIGO ---
# TODO 1: split 80/20 estratificado, random_state=42
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y_raw, test_size=0.2, random_state=42, stratify=y_raw
)

# TODO 2: StandardScaler — fit SOLO sobre train
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f'Train: {X_train_sc.shape}  '
      f'Pulgar abajo: {(y_train==0).sum()}  Pulgar arriba: {(y_train==1).sum()}')
print(f'Test:  {X_test_sc.shape}   '
      f'Pulgar abajo: {(y_test==0).sum()}   Pulgar arriba: {(y_test==1).sum()}')
print(f'\nTrain escalado — mean~{X_train_sc.mean():.4f}  std~{X_train_sc.std():.4f}')

"""---
## Ejercicio 5 — Curvas de aprendizaje

### Paso 5.1 — Diagnosticar overfitting

| Patrón | Diagnóstico | Solución |
|---|---|---|
| $E_{train} \approx E_{val}$ ambos altos | Underfitting | Más capacidad |
| $E_{train} \ll E_{val}$, brecha grande | Overfitting | Regularización, más datos |
| $E_{train} \approx E_{val}$ ambos bajos | Ajuste correcto | ✓ |

"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
train_sizes = np.linspace(0.1, 1.0, 8)

modelos = {
    'SVM Lineal (C=1)': SVC(kernel='linear', C=1, random_state=42),
    'SVM RBF   (C=1)':  SVC(kernel='rbf', C=1, gamma='scale', random_state=42),
}

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, (nombre, modelo) in zip(axes, modelos.items()):

    # --- COMPLETA EL CÓDIGO ---
    ts, tr_sc, val_sc = learning_curve(
        modelo, X_train_sc, y_train,
        train_sizes=train_sizes, cv=cv,
        scoring='accuracy', n_jobs=-1
    )
    tr_m  = tr_sc.mean(axis=1);  tr_s  = tr_sc.std(axis=1)
    val_m = val_sc.mean(axis=1); val_s = val_sc.std(axis=1)
    brecha = float(tr_m[-1] - val_m[-1])

    ax.plot(ts, tr_m,  'o--', color=UPCH_BLUE, lw=2, label='Train')
    ax.fill_between(ts, tr_m-tr_s, tr_m+tr_s, alpha=0.15, color=UPCH_BLUE)
    ax.plot(ts, val_m, 's-',  color=UPCH_RED,  lw=2, label='Validacion (CV-5)')
    ax.fill_between(ts, val_m-val_s, val_m+val_s, alpha=0.15, color=UPCH_RED)
    ax.set_title(f'{nombre}\nBrecha final: {brecha:.3f}',
                 fontsize=11, fontweight='bold', color=UPCH_RED)
    ax.set_xlabel('Muestras de entrenamiento', fontsize=10)
    ax.set_ylabel('Accuracy', fontsize=10)
    ax.set_ylim(0.5, 1.05)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

plt.suptitle('Curvas de Aprendizaje — EMG: Pulgar abajo vs Pulgar arriba',
             fontsize=12, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('curvas_aprendizaje_emg.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 5.2 — Interpreta las curvas

1. ¿Qué modelo tiene mayor brecha $\Delta_{gen}$? ¿Hay overfitting?
2. ¿Agregar más registros EMG mejoraría el modelo? ¿Cómo lo sabes mirando la curva?
3. ¿Qué kernel elegirías para una prótesis en tiempo real? Considera también la velocidad de predicción.

**📝 Tu respuesta:**
1. **SVM RBF** suele mostrar mayor brecha. Esto indica cierto overfitting, ya que memoriza patrones del train que no generalizan perfecto. El Lineal tiene menor brecha porque su frontera más simple regulariza implícitamente.
2. Si la curva de validación aún tiene pendiente positiva (no se ha aplanado del todo), sí ayudarían más registros, porque indica que el modelo sigue aprendiendo patrones generalizables con más datos.
3. Elegiría **SVM Lineal** si la diferencia de accuracy es pequeña. Predice en $O(d)$ mientras que RBF en $O(N_{sv} \times d)$. En tiempo real, la baja latencia es crítica para evitar retardos en la prótesis.

---
## Ejercicio 6 — Selección de C con CV-5

### Paso 6.1 — Barrido de C en escala logarítmica

> **Anti-leakage:** el barrido se realiza **solo sobre train**. El test set no se toca hasta el paso final.

$$\min_{w,b,\xi} \;\frac{1}{2}\|w\|^2 + C\sum_{i=1}^{n}\xi_i$$
"""

C_values = [0.001, 0.01, 0.1, 1, 10]
acc_lineal, acc_rbf = [], []

# --- COMPLETA EL CÓDIGO ---
# TODO: para cada C entrena SVM Lineal y RBF con cross_val_score
# cv=cv, scoring='accuracy' — guarda el promedio de 5 folds
# imprime los resultados por cada C

for C in C_values:
    svm_lin = SVC(kernel='linear', C=C, random_state=42)
    svm_rbf = SVC(kernel='rbf',    C=C, gamma='scale', random_state=42)
    sc_lin  = cross_val_score(svm_lin, X_train_sc, y_train, cv=cv, scoring='accuracy').mean()
    sc_rbf  = cross_val_score(svm_rbf, X_train_sc, y_train, cv=cv, scoring='accuracy').mean()
    acc_lineal.append(sc_lin)
    acc_rbf.append(sc_rbf)
    print(f'C={C:>6}   Lineal: {sc_lin:.4f}   RBF: {sc_rbf:.4f}')

C_opt_lin = C_values[int(np.argmax(acc_lineal))]
C_opt_rbf = C_values[int(np.argmax(acc_rbf))]
print(f'\nC optimo Lineal: {C_opt_lin}  (CV acc = {max(acc_lineal):.4f})')
print(f'C optimo RBF:    {C_opt_rbf}  (CV acc = {max(acc_rbf):.4f})')

# --- COMPLETA EL CÓDIGO ---
# TODO: grafica acc_lineal y acc_rbf vs C_values en escala log
# UPCH_BLUE para Lineal, UPCH_RED para RBF
# Incluye líneas verticales en C_opt_lin y C_opt_rbf

fig, ax = plt.subplots(figsize=(9, 4))
ax.semilogx(C_values, acc_lineal, 'o--', color=UPCH_BLUE, lw=2, markersize=8, label='SVM Lineal')
ax.semilogx(C_values, acc_rbf,    's-',  color=UPCH_RED,  lw=2, markersize=8, label='SVM RBF')
ax.axvline(C_opt_lin, color=UPCH_BLUE, ls=':', lw=1.5, label=f'C* Lineal = {C_opt_lin}')
ax.axvline(C_opt_rbf, color=UPCH_RED,  ls=':', lw=1.5, label=f'C* RBF    = {C_opt_rbf}')
ax.set_xlabel('Valor de C (escala log)', fontsize=11)
ax.set_ylabel('Accuracy (CV-5)', fontsize=11)
ax.set_title('Efecto de C — SVM sobre EMG: Pulgar abajo vs Pulgar arriba',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('barrido_C_emg.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## Ejercicio 7 — Evaluación final EMG

### Paso 7.1 — Test set (una sola vez)

> Usa los C óptimos ya seleccionados. **No ajustes nada más después de ver el test.**

"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: entrena SVM Lineal (C_opt_lin) y RBF (C_opt_rbf) sobre X_train_sc
svm_lin_final = SVC(kernel='linear', C=C_opt_lin, random_state=42)
svm_rbf_final = SVC(kernel='rbf',    C=C_opt_rbf, gamma='scale', random_state=42)
svm_lin_final.fit(X_train_sc, y_train)
svm_rbf_final.fit(X_train_sc, y_train)

# TODO 2: predice sobre X_test_sc
y_pred_lin = svm_lin_final.predict(X_test_sc)
y_pred_rbf = svm_rbf_final.predict(X_test_sc)

acc_lin = accuracy_score(y_test, y_pred_lin)
acc_rbf = accuracy_score(y_test, y_pred_rbf)

print('=' * 60)
print('    EVALUACION FINAL — SVM sobre EMG Gestos')
print('=' * 60)
print(f'{"Modelo":<20} {"C*":<8} {"Accuracy":<12} {"SVs"}')
print('-' * 60)
print(f'{"SVM Lineal":<20} {C_opt_lin:<8} {acc_lin:.4f}       '
      f'{svm_lin_final.n_support_.sum()}')
print(f'{"SVM RBF":<20} {C_opt_rbf:<8} {acc_rbf:.4f}       '
      f'{svm_rbf_final.n_support_.sum()}')

# --- COMPLETA EL CÓDIGO ---
# TODO: matrices de confusion lado a lado
# display_labels=['Pulgar abajo', 'Pulgar arriba'], cmap='Reds'

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
etiquetas = ['Pulgar abajo', 'Pulgar arriba']

for ax, nombre, y_pred, acc in zip(
    axes,
    ['SVM Lineal', 'SVM RBF'],
    [y_pred_lin, y_pred_rbf],
    [acc_lin, acc_rbf]
):
    cm = confusion_matrix(y_test, y_pred)
    ConfusionMatrixDisplay(confusion_matrix=cm,
                           display_labels=etiquetas).plot(ax=ax, cmap='Reds', colorbar=False)
    ax.set_title(f'{nombre}\nAccuracy test = {acc:.4f}',
                 fontsize=11, fontweight='bold', color=UPCH_RED)

plt.suptitle('Matrices de Confusion — SVM sobre EMG Gestos',
             fontsize=12, fontweight='bold', color=UPCH_RED, y=1.02)
plt.tight_layout()
plt.savefig('cm_svm_emg.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 7.2 — Métricas clínicas

"""

# --- COMPLETA EL CÓDIGO ---
# TODO: tabla comparativa accuracy, recall, precision, F1 para ambos modelos
# Clase positiva = 1 (pulgar arriba)

print(f'{"Modelo":<20} {"Accuracy":<12} {"Recall":<12} {"Precision":<12} {"F1"}')
print('-' * 65)
for nombre, y_pred in [('SVM Lineal', y_pred_lin), ('SVM RBF', y_pred_rbf)]:
    acc  = accuracy_score(y_test, y_pred)
    rec  = recall_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    f1   = f1_score(y_test, y_pred)
    print(f'{nombre:<20} {acc:<12.4f} {rec:<12.4f} {prec:<12.4f} {f1:.4f}')

print()
print('→ Para una protesis en tiempo real: ¿accuracy o velocidad de prediccion?')
print('  SVM Lineal predice en O(d), SVM RBF predice en O(N_sv x d).')
print('  Si la diferencia de accuracy es <2%, ¿cuál elegirías? ¿Por qué?')
print()
print('📝 Tu respuesta: Elegiría SVM Lineal. En prótesis tiempo real la latencia es crítica. SVM Lineal predice mucho más rápido y es más fácil de desplegar en hardware embebido.')

"""---
# PARTE 2 — Imagen MRI: Tumor Cerebral

## Ejercicio 8 — Carga y preprocesamiento

El dataset **Brain Tumor MRI** contiene imágenes de resonancia magnética:
- **notumor** → cerebro sano (clase 0)
- **tumor** → glioma, meningioma o tumor pituitario agrupados (clase 1)

Pipeline:
$$I \in \mathbb{R}^{150 \times 150} \xrightarrow{\text{flatten}} x \in \mathbb{R}^{22500} \xrightarrow{\text{PCA}} z \in \mathbb{R}^{d} \xrightarrow{\text{SVM-RBF}} \hat{y}$$

### Paso 8.1 — Carga de imágenes

"""

# en este caso la siguiente linea ha sido reemplazada pues no estamos cargando directamente desde local
# DATA_DIR = BASE / 'brain_tumor'

def cargar_brain_mri(base_dir, split='Training', max_por_clase=120, target_size=(150, 150)):
    from pathlib import Path
    base_dir = Path(base_dir)
    candidates = list(base_dir.glob(f'**/{split}'))
    if not candidates:
        raise FileNotFoundError(f'No se encontro la carpeta {split} en {base_dir}')
    split_dir = candidates[0]

    imgs, labels = [], []
    ruta_sano = split_dir / 'notumor'
    for ruta in (list(ruta_sano.glob('*.jpg')) +
                 list(ruta_sano.glob('*.jpeg')))[:max_por_clase]:
        img = cv2.imread(str(ruta), cv2.IMREAD_GRAYSCALE)
        if img is not None:
            imgs.append(cv2.resize(img, target_size).astype(np.float32) / 255.0)
            labels.append(0)
    for tipo in ['glioma', 'meningioma', 'pituitary']:
        ruta_t = split_dir / tipo
        if not ruta_t.exists():
            continue
        for ruta in (list(ruta_t.glob('*.jpg')) +
                     list(ruta_t.glob('*.jpeg')))[:max_por_clase // 3]:
            img = cv2.imread(str(ruta), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                imgs.append(cv2.resize(img, target_size).astype(np.float32) / 255.0)
                labels.append(1)
    return np.array(imgs), np.array(labels)

imgs_train, y_img_train = cargar_brain_mri(DATA_DIR_MRI, 'Training',  max_por_clase=120)
imgs_test,  y_img_test  = cargar_brain_mri(DATA_DIR_MRI, 'Testing',   max_por_clase=40)
print(f'Train: {imgs_train.shape}  '
      f'NoTumor: {(y_img_train==0).sum()}  Tumor: {(y_img_train==1).sum()}')
print(f'Test:  {imgs_test.shape}   '
      f'NoTumor: {(y_img_test==0).sum()}   Tumor: {(y_img_test==1).sum()}')

"""### Paso 8.2 — EDA: visualizar ejemplos
> ¿Qué diferencias morfológicas observas entre cerebro con tumor y sin tumor?

"""

fig, axes = plt.subplots(2, 4, figsize=(14, 7))
for row, (clase_str, clase_id, color) in enumerate([
    ('Sin Tumor', 0, UPCH_BLUE),
    ('Con Tumor', 1, UPCH_RED)
]):
    idx_c = np.where(y_img_train == clase_id)[0]
    for col in range(3):
        ax = axes[row, col]
        ax.imshow(imgs_train[idx_c[col]], cmap='gray', vmin=0, vmax=1)
        if col == 0:
            ax.set_ylabel(clase_str, fontsize=11, fontweight='bold', color=color)
        ax.axis('off')
    ax_h = axes[row, 3]
    for i in idx_c[:8]:
        ax_h.hist(imgs_train[i].flatten(), bins=50, alpha=0.2, color=color)
    ax_h.set_title(f'Intensidades\n{clase_str}', fontsize=9, fontweight='bold')
    ax_h.set_xlabel('[0,1]', fontsize=8)
plt.suptitle('Brain Tumor MRI — EDA por clase',
             fontsize=13, fontweight='bold', color=UPCH_RED, y=1.01)
plt.tight_layout()
plt.savefig('eda_brain_mri.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## Ejercicio 9 — PCA sobre MRI cerebral

### Paso 9.1 — Flatten + StandardScaler + varianza explicada

> **Anti-leakage:** `StandardScaler` y `PCA` se ajustan **solo sobre train**. En la realidad clínica, cuando llega una nueva imagen, se proyecta con el scaler y PCA aprendidos del train — nunca se recalculan.

"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: flatten las imágenes (reshape a 2D)
X_flat_train = imgs_train.reshape(len(imgs_train), -1)   # shape esperada: (N_train, 22500)
X_flat_test  = imgs_test.reshape(len(imgs_test), -1)     # shape esperada: (N_test,  22500)
print(f'Flatten — Train: {X_flat_train.shape}   Test: {X_flat_test.shape}')

# TODO 2: StandardScaler — fit SOLO sobre train
scaler_mri = StandardScaler()
X_sc_train = scaler_mri.fit_transform(X_flat_train)
X_sc_test  = scaler_mri.transform(X_flat_test)

# Varianza explicada
pca_exp = PCA(n_components=100, random_state=42)
pca_exp.fit(X_sc_train)
var_acum = np.cumsum(pca_exp.explained_variance_ratio_)

fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(range(1, 101), var_acum, color=UPCH_RED, lw=2)
ax.axhline(0.90, color='gray', ls='--', lw=1.5, label='90% varianza')
ax.axhline(0.95, color='navy', ls='--', lw=1.5, label='95% varianza')
n_90 = int(np.argmax(var_acum >= 0.90)) + 1
n_95 = int(np.argmax(var_acum >= 0.95)) + 1
ax.axvline(n_90, color='gray', ls=':', lw=1.2, label=f'n={n_90} para 90%')
ax.axvline(n_95, color='navy', ls=':', lw=1.2, label=f'n={n_95} para 95%')
ax.set_xlabel('Numero de componentes PCA', fontsize=11)
ax.set_ylabel('Varianza acumulada', fontsize=11)
ax.set_title('PCA — Brain Tumor MRI',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('pca_varianza_mri.png', dpi=150, bbox_inches='tight')
plt.show()

# --- COMPLETA EL CÓDIGO ---
# TODO: ajusta PCA con N_COMP=80, transforma train y test

N_COMP = 80
pca    = PCA(n_components=N_COMP, random_state=42)
Z_train = pca.fit_transform(X_sc_train)   # fit_transform SOLO sobre X_sc_train
Z_test  = pca.transform(X_sc_test)        # transform sobre X_sc_test (no fit)

print(f'Reduccion: {X_sc_train.shape[1]:,} → {N_COMP} features '
      f'({pca.explained_variance_ratio_.sum():.1%} varianza conservada)')

"""---
## Ejercicio 10 — SVM-RBF sobre MRI cerebral

### Paso 10.1 — Selección de C con CV-5

$$K(z_i, z_j) = \exp\left(-\gamma \|z_i - z_j\|^2\right)$$

"""

C_values_mri = [0.01, 0.1, 1, 10]
cv_mri = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# --- COMPLETA EL CÓDIGO ---
# TODO: barrido de C para SVM-RBF sobre Z_train, y_img_train
# imprime el resultado por cada C

acc_cv_mri = []
for C in C_values_mri:
    svm_mri = SVC(kernel='rbf', C=C, gamma='scale', random_state=42)
    sc = cross_val_score(svm_mri, Z_train, y_img_train,
                         cv=cv_mri, scoring='accuracy').mean()
    acc_cv_mri.append(sc)
    print(f'C={C:>6}   CV accuracy = {sc:.4f}')

C_opt_mri = C_values_mri[int(np.argmax(acc_cv_mri))]
print(f'\nC optimo MRI: {C_opt_mri}  (CV acc = {max(acc_cv_mri):.4f})')

# --- COMPLETA EL CÓDIGO ---
# TODO: entrena modelo final, predice en test, matriz de confusion

svm_mri_final = SVC(kernel='rbf', C=C_opt_mri, gamma='scale', random_state=42)
svm_mri_final.fit(Z_train, y_img_train)
y_pred_mri = svm_mri_final.predict(Z_test)
acc_mri    = accuracy_score(y_img_test, y_pred_mri)

print(f'SVM-RBF Brain MRI (C={C_opt_mri}) — Accuracy test: {acc_mri:.4f}')
print()
print(classification_report(y_img_test, y_pred_mri,
                             target_names=['Sin Tumor', 'Con Tumor']))

fig, ax = plt.subplots(figsize=(5.5, 4.5))
ConfusionMatrixDisplay(
    confusion_matrix=confusion_matrix(y_img_test, y_pred_mri),
    display_labels=['Sin Tumor', 'Con Tumor']
).plot(ax=ax, cmap='Reds', colorbar=False)
ax.set_title(f'SVM RBF — Brain Tumor MRI\nAccuracy = {acc_mri:.4f}',
             fontsize=12, fontweight='bold', color=UPCH_RED)
plt.tight_layout()
plt.savefig('cm_svm_mri.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## Ejercicio 11 — Curva de aprendizaje MRI
### ¿Necesitamos más imágenes?

"""

# --- COMPLETA EL CÓDIGO ---
# TODO: curva de aprendizaje SVM-RBF con C_opt_mri sobre Z_train
# train_sizes = np.linspace(0.15, 1.0, 7)
# Grafica train (UPCH_BLUE) y val (UPCH_RED) con banda ±1std
# Incluye la brecha final en el título

train_sizes_mri = np.linspace(0.15, 1.0, 7)
svm_lc_mri = SVC(kernel='rbf', C=C_opt_mri, gamma='scale', random_state=42)

ts_mri, tr_mri, val_mri = learning_curve(
    svm_lc_mri, Z_train, y_img_train,
    train_sizes=train_sizes_mri, cv=cv_mri,
    scoring='accuracy', n_jobs=-1
)

fig, ax = plt.subplots(figsize=(9, 4))
ax.plot(ts_mri, tr_mri.mean(axis=1),  'o--', color=UPCH_BLUE, lw=2, label='Train')
ax.fill_between(ts_mri,
                tr_mri.mean(axis=1) - tr_mri.std(axis=1),
                tr_mri.mean(axis=1) + tr_mri.std(axis=1),
                alpha=0.15, color=UPCH_BLUE)
ax.plot(ts_mri, val_mri.mean(axis=1), 's-', color=UPCH_RED, lw=2, label='Validacion (CV-5)')
ax.fill_between(ts_mri,
                val_mri.mean(axis=1) - val_mri.std(axis=1),
                val_mri.mean(axis=1) + val_mri.std(axis=1),
                alpha=0.15, color=UPCH_RED)
brecha_mri = float(tr_mri.mean(axis=1)[-1] - val_mri.mean(axis=1)[-1])
ax.set_title(f'Curva de Aprendizaje — SVM RBF sobre Brain Tumor MRI\n'
             f'Brecha final: {brecha_mri:.3f}',
             fontsize=12, fontweight='bold', color=UPCH_RED)
ax.set_xlabel('Imagenes de entrenamiento', fontsize=10)
ax.set_ylabel('Accuracy', fontsize=10)
ax.set_ylim(0.5, 1.05)
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('curva_aprendizaje_mri.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Interpreta la curva

1. ¿La curva de validación sigue subiendo? → ¿Más imágenes MRI ayudarían?
2. Compara la brecha de MRI con la brecha de EMG. ¿Por qué son distintas?
3. ¿Qué limitación tiene SVM+PCA para imágenes médicas que CNN no tiene?

**📝 Tu respuesta:**
1. Sí, la curva sigue subiendo (no se ha aplanado por completo), lo que indica que más imágenes ayudarían al modelo a aprender patrones y mejorar su generalización.
2. La brecha en MRI es mayor porque las imágenes tienen más variabilidad interindividual y el tamaño del dataset es mucho menor que el de señales EMG. Además, PCA capta varianza global que diluye las características locales de los tumores.
3. SVM+PCA no preserva la información espacial local. Texturas, bordes y asimetrías de un tumor se pierden al aplanar la imagen, mientras que las CNN usan filtros convolucionales que sí capturan y mantienen esa relación espacial clave.

---
## Ejercicio 12 — Análisis final comparativo
### Paso 12.1 — Tabla de métricas
"""

# --- COMPLETA EL CÓDIGO ---
# TODO: tabla comparativa — usa el mejor modelo de EMG

# Determinar mejor modelo EMG
if max(acc_lineal) >= max(acc_rbf):
    best_emg_name = 'SVM Lineal'
    best_emg_pred = y_pred_lin
else:
    best_emg_name = 'SVM RBF'
    best_emg_pred = y_pred_rbf

# Calcular metricas EMG
emg_acc  = accuracy_score(y_test, best_emg_pred)
emg_rec  = recall_score(y_test, best_emg_pred)
emg_prec = precision_score(y_test, best_emg_pred)
emg_f1   = f1_score(y_test, best_emg_pred)

# Calcular metricas MRI
mri_rec  = recall_score(y_img_test, y_pred_mri)
mri_prec = precision_score(y_img_test, y_pred_mri)
mri_f1   = f1_score(y_img_test, y_pred_mri)

print('=' * 70)
print('         RESUMEN FINAL — Challenge 3')
print('=' * 70)
print(f'{"Dataset":<20} {"Modelo":<15} '
      f'{"Accuracy":<12} {"Recall":<12} {"Precision":<12} {"F1"}')
print('-' * 70)
# EMG — mejor modelo
print(f'{"EMG Gestos":<20} {best_emg_name:<15} '
      f'{emg_acc:<12.4f} {emg_rec:<12.4f} {emg_prec:<12.4f} {emg_f1:.4f}')
# Brain MRI
print(f'{"Brain MRI":<20} {"SVM RBF":<15} '
      f'{acc_mri:<12.4f} {mri_rec:<12.4f} {mri_prec:<12.4f} {mri_f1:.4f}')

"""### Paso 12.2 — Reflexión clínica final

Completa la tabla:

| Escenario | Dataset | Modelo | Métrica prioritaria | Justificación |
|---|---|---|---|---|
| Prótesis mioeléctrica tiempo real | EMG | SVM Lineal | F1 / Latencia | Se necesita balance entre precision y recall, pero la latencia (O(d)) es crítica para que no haya retardos físicos. |
| Screening tumor cerebral | MRI | SVM RBF | Recall (Sensibilidad) | En screening médico se prioriza detectar todos los tumores (minimizar FN), ya que un falso negativo puede ser fatal. |
| Sistema embebido de bajo consumo | EMG | SVM Lineal | Accuracy + Memoria | Requiere menos parámetros, operaciones más rápidas y menos consumo energético para microcontroladores. |

**📝 Tu respuesta:** Los datasets muestran el trade-off sesgo-varianza desde lados distintos. EMG se separa casi linealmente con buenas features estadísticas, pero MRI sufre porque PCA rompe las relaciones espaciales locales del tumor. Por esto último las redes CNN dominan actualmente en análisis de imagen.

---
<div style='background:#f5f5f5; padding:15px; border-left:5px solid #8B0000; border-radius:4px'>
<b>Entrega:</b> Sube tu notebook ejecutado (.ipynb con outputs) a tu carpeta de GitHub del curso.<br>
<b>Nombre del archivo:</b> <code>Challenge3_ApellidoNombreDeAmbos.ipynb</code><br>
<b>Fecha límite:</b> antes de Clase 5
</div>
"""

