# -*- coding: utf-8 -*-
"""Clase3_Challenge2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVBWMj1TXYu1BzM0He-WBcu8fl-2ZjEo

<div style='background:#8B0000; padding:20px; border-radius:8px; margin-bottom:10px'>
<h1 style='color:white; text-align:center; margin:0'>Reconocimiento de Patrones</h1>
<h2 style='color:#ffcccc; text-align:center; margin:5px 0 0 0'>Challenge 2 — Clasificación con k-NN y Naive Bayes</h2>
<p style='color:#ffaaaa; text-align:center; margin:5px 0 0 0'>Ingeniería Biomédica · UPCH · 2026-1</p>
</div>

## Contexto clínico

Se te proporciona el dataset **Pima Indians Diabetes** (NIDDK, 1988), un clásico benchmark biomédico que contiene registros de **768 mujeres** con variables metabólicas y demográficas. La variable objetivo es `Outcome` (0 = no diabética, 1 = diabética con diabetes mellitus tipo 2).

Tu misión: construir, evaluar y comparar un clasificador **k-NN** y un **Naive Bayes Gaussiano** para predecir diabetes a partir de variables clínicas. Para cada decisión de diseño deberás **justificar clínicamente** tu elección.

---
> **Dataset:** `diabetes.csv`  
> **Fuente:** Smith, J.W. et al. (1988). *Using the ADAP Learning Algorithm to Forecast the Onset of Diabetes Mellitus*. Proceedings of the Annual Symposium on Computer Application in Medical Care.  
> Disponible en: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database

---

### Variables del dataset

| Variable | Descripción | Unidad |
|---|---|---|
| Pregnancies | Número de embarazos | — |
| Glucose | Glucosa plasmática en ayunas (OGTT 2h) | mg/dL |
| BloodPressure | Presión arterial diastólica | mmHg |
| SkinThickness | Grosor del pliegue tricipital | mm |
| Insulin | Insulina sérica a las 2h | μU/mL |
| BMI | Índice de masa corporal | kg/m² |
| DiabetesPedigreeFunction | Score hereditario de diabetes | — |
| Age | Edad | años |
| **Outcome** | **Diagnóstico de diabetes** | **0/1** |

<div style='background:#e8f5e9; padding:8px 14px; border-left:4px solid #2e7d32; border-radius:4px; margin:8px 0'>
⏱️ <b>EN CLASE</b> — completa esto durante la sesión
</div>

---
## Ejercicio 1 — Diseño previo al código (conceptual)

> **Antes de escribir una línea de código**, razona sobre el problema.

### 1.1 — ¿k-NN o Naive Bayes? ¿O ambos?

Para este dataset de variables clínicas continuas, responde **antes de ver los datos**:

1. ¿Qué suposición hace Naive Bayes sobre las features? ¿Es razonable para glucosa, IMC y presión arterial? ¿Por qué?
2. k-NN requiere escalar los datos. Si no lo hicieras, ¿qué feature dominaría la distancia euclidiana y por qué? (pista: revisa las unidades de la tabla)
3. Para un sistema de tamizaje masivo (screening) de diabetes en una posta médica, ¿priorizarías **recall** o **precision**? Argumenta clínicamente.
4. Si la prevalencia de diabetes en la población fuera solo 5% (vs ~35% en este dataset), ¿cómo afectaría eso a la interpretación del posterior de Naive Bayes?

**📝 Tu respuesta (edita esta celda):**
1. Se asume que todas las features son condicionalmente independientes entre sí. No es razonable, porque las variables fisiológicas suelen estar metabólicamente relacionadas
2. Dominaría la feature Insulin, porque sus valores pueden llegar a 800. Como k-NN calcula distancias geométricas, la insulina opacaría al resto de variables
3. En un tamizaje clínico es preferible tener un falso positivo que un falso negativo
4. Si la prevalencia fuera así de baja, la probabilidad a priori se reduce drásticamente. El Naive Bayes se volvería más conservador al predecir, lo que probablemente disminuiría los falsos positivos pero también hará caer el recall

### 1.2 — Pipeline completo

Dibuja (en texto o diagrama) el pipeline que vas a implementar, indicando **en qué paso** se hace el train/test split y por qué es importante no cruzar esa frontera.

```
diabetes.csv
    │
    ▼
[ Paso A ] __Limpieza de datos__  ← ¿Qué haces aquí?
    │
    ▼
[ Paso B ] __División de datos (Train/Test Split)___  ← ¿Aquí ya haces el split? ¿Por qué? Porque se debe serparar los datos antes de imputar o escalar para evitar la fuga de datos (leakeage)
    │
    ├──────── TRAIN ──────────────────────────────────────────────┐
    │                                                             │
    ▼                                                             │
[ Paso C ] _Imputación (calcular mediana) y Escalado (media/desviación) *solo con train___  ← ¿Qué estimas SOLO con train?        │
    │                                                             │
    ▼                                                             │
[ Paso D ] __Ajuste de hiperparámetros como *k*___  ← Entrenamiento de modelos            │
    │                                                             │
    └──────── TEST ── (aplicas lo estimado en C) ─────────────────┘
    │
    ▼
[ Paso E ] ___set del Test intacto___  ← Evaluación final
```

**📝 Tu respuesta (edita esta celda):** completa los `___` del diagrama.

---
## Ejercicio 2 — Setup y carga de datos
"""

# ── Conexión con Google Drive ──────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# Colores UPCH
UPCH_RED  = '#8B0000'
UPCH_BLUE = '#1565C0'
UPCH_GRAY = '#4A4A4A'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, confusion_matrix,
                              classification_report, ConfusionMatrixDisplay,
                              precision_score, recall_score, f1_score)
from sklearn.pipeline import Pipeline

# Ruta del dataset
DATA_PATH = Path('/content/drive/MyDrive/Rec. Patrones/Challenge_2')/'diabetes.csv'

print('Librerías cargadas correctamente ✓')

"""### Paso 2.1 — Carga y primera inspección"""

df = pd.read_csv(DATA_PATH)

print(f'Shape: {df.shape}')
print(f'\nPrimeras filas:')
df.head()

# Tipos de datos y valores nulos
print('Tipos de datos:')
print(df.dtypes)
print(f'\nValores nulos por columna:')
print(df.isnull().sum())
print(f'\nEstadísticas descriptivas:')
df.describe()

"""### Paso 2.2 — Distribución de clases y desbalance"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: calcula el conteo y porcentaje de cada clase en 'Outcome'
conteo = df['Outcome'].value_counts().sort_index()
pct    = df['Outcome'].value_counts(normalize=True).sort_index() * 100

print('Distribución de clases:')
print(f'  No diabética (0): {conteo[0]} pacientes ({pct[0]:.1f}%)')
print(f'  Diabética    (1): {conteo[1]} pacientes ({pct[1]:.1f}%)')

fig, ax = plt.subplots(figsize=(5, 4))

# TODO 2: grafica las barras con colores [UPCH_BLUE, UPCH_RED]
barras = ax.bar([0, 1], conteo, color=[UPCH_BLUE, UPCH_RED])

ax.set_title('Distribución de clases — Diabetes', fontweight='bold', color=UPCH_RED)
ax.set_xticks([0, 1])
ax.set_xticklabels(['No diabética (0)', 'Diabética (1)'])
ax.set_ylabel('Número de pacientes')

# TODO 3: agrega el valor numérico y porcentaje encima de cada barra
for i, barra in enumerate(barras):
    altura = barra.get_height()
    ax.text(barra.get_x() + barra.get_width()/2., altura + 5,
            f'{int(altura)}\n({pct[i]:.1f}%)',
            ha='center', va='bottom', fontweight='bold', color=UPCH_GRAY)

plt.tight_layout()
plt.savefig('distribucion_diabetes.png', dpi=150, bbox_inches='tight')
plt.show()
print('→ ¿Hay desbalance? ¿Qué clasificador trivial daría accuracy alta sin detectar nada útil?')

"""---
## Ejercicio 3 — Limpieza: valores fisiológicamente imposibles

Este dataset tiene un problema clásico: variables como Glucosa, BloodPressure, BMI e Insulin tienen valores **0** que son fisiológicamente imposibles. Son errores de adquisición codificados como 0 en lugar de `NaN`.
"""

# Columnas que NO pueden ser 0 fisiológicamente
cols_no_cero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

print('Valores = 0 por columna (antes de limpiar):')
for col in cols_no_cero:
    n_cero = (df[col] == 0).sum()
    print(f'  {col:<25} {n_cero:>4} ({100*n_cero/len(df):.1f}%)')

df_clean = df.copy()

# --- COMPLETA EL CÓDIGO ---
# TODO: reemplaza los valores 0 por NaN en todas las columnas de cols_no_cero
# Pista: usa un loop o df_clean[cols_no_cero].replace()
df_clean[cols_no_cero] = df_clean[cols_no_cero].replace(0, np.nan)

print('Valores NaN tras limpieza:')
print(df_clean[cols_no_cero].isnull().sum())
print('\n→ La imputación se realizará DESPUÉS del split, solo con estadísticas de train.')

"""---
## Ejercicio 4 — EDA: ¿qué features separan mejor las clases?

Antes de entrenar cualquier modelo, exploramos visualmente qué variables tienen más **poder discriminativo**.
"""

features_num = ['Glucose', 'BMI', 'Age', 'DiabetesPedigreeFunction', 'BloodPressure', 'Insulin']

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i, feat in enumerate(features_num):
    ax = axes[i]

    # --- COMPLETA EL CÓDIGO ---
    # TODO: grafica histogramas superpuestos (density=True) para clase 0 y clase 1
    # Usa alpha=0.6, UPCH_BLUE para clase 0, UPCH_RED para clase 1
    # Agrega una línea vertical con la media de cada clase
    for clase, color, label in [(0, UPCH_BLUE, 'No diabética'), (1, UPCH_RED, 'Diabética')]:
        valores = df_clean[df_clean['Outcome'] == clase][feat].dropna()
        # TODO: hist y línea de media
        ax.hist(valores, bins=20, alpha=0.6, color=color, density=True, label=label)
        ax.axvline(valores.mean(), color=color, linestyle='dashed', linewidth=2)


    ax.set_title(feat, fontweight='bold', fontsize=11)
    ax.set_xlabel('Valor', fontsize=9)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

fig.suptitle('EDA — Distribuciones por clase: ¿qué features discriminan mejor?',
             fontsize=13, fontweight='bold', color=UPCH_RED)
plt.tight_layout()
plt.savefig('eda_diabetes.png', dpi=150, bbox_inches='tight')
plt.show()
print('→ ¿Qué feature tiene las distribuciones más separadas? ¿Cuál tiene más solapamiento?')

"""### Paso 4.2 — Mapa de correlación

Naive Bayes asume independencia condicional. ¿Hay correlaciones fuertes entre features?
"""

# --- COMPLETA EL CÓDIGO ---
# TODO: calcula la matriz de correlación de df_clean (solo features numéricas, sin Outcome)
#       y grafícala con seaborn heatmap. Incluye: cmap='RdBu_r', vmin=-1, vmax=1, annot=True

plt.figure(figsize=(8, 6))
matriz_corr = df_clean.drop('Outcome', axis=1).corr()
sns.heatmap(matriz_corr, cmap='RdBu_r', vmin=-1, vmax=1, annot=True, fmt=".2f")
plt.title("Matriz de Correlación de Variables Clínicas")
plt.show()

print('→ Identifica los pares de features con |correlación| > 0.5.')
print('  ¿Viola esto la suposición de Naive Bayes? ¿Cuánto impacto tendrá?')

"""---
## Ejercicio 5 — Preprocesamiento: split, imputación y escalado
"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: separa features (X) y target (y) de df_clean
X = df_clean.drop('Outcome', axis=1)
y = df_clean['Outcome']

# TODO 2: haz train_test_split con test_size=0.2, random_state=42, estratificado
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f'Train: {X_train.shape}  →  {(y_train==1).sum()} diabéticas ({100*(y_train==1).mean():.1f}%)')
print(f'Test:  {X_test.shape}   →  {(y_test==1).sum()} diabéticas ({100*(y_test==1).mean():.1f}%)')

# --- COMPLETA EL CÓDIGO ---
# TODO: imputa los NaN con la MEDIANA de train (no de todo el dataset)
#       Aplica la mediana de train también al test

mediana_train = X_train.median()
X_train_imp   = X_train.fillna(mediana_train)
X_test_imp    = X_test.fillna(mediana_train)

print(f'NaN en train tras imputación: {np.isnan(X_train_imp).sum()}')
print(f'NaN en test  tras imputación: {np.isnan(X_test_imp).sum()}')

# --- COMPLETA EL CÓDIGO ---
# TODO: escala con StandardScaler
#       - fit_transform sobre X_train_imp
#       - transform (sin fit) sobre X_test_imp

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train_imp)
X_test_sc  = scaler.transform(X_test_imp)

print(f'Train escalado — media: {X_train_sc.mean():.4f}  std: {X_train_sc.std():.4f}')

"""---
## Ejercicio 6 — Entrenamiento de modelos

### Paso 6.1 — Naive Bayes Gaussiano
"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: entrena un GaussianNB con X_train_imp (NB no necesita escalado, usa datos imputados)
gnb = GaussianNB()
gnb.fit(X_train_imp, y_train) # Entrenamos con datos imputados, sin escalar

# TODO 2: predice sobre X_test_imp
y_pred_gnb = gnb.predict(X_test_imp)

# TODO 3: imprime accuracy
acc_gnb = accuracy_score(y_test, y_pred_gnb)
print(f'Naive Bayes — Accuracy: {acc_gnb:.4f}')

"""### Paso 6.2 — k-NN: selección de k óptimo

Entrena k-NN para **k = 1, 3, 5, 7, 9, 11, 15** usando validación interna sobre train (80/20). Grafica train vs val accuracy y selecciona k óptimo.
"""

# --- COMPLETA EL CÓDIGO ---
# TODO 1: divide X_train_sc / y_train en subconjuntos train_sub / val (80/20, estratificado)
X_tr_sub, X_val, y_tr_sub, y_val = train_test_split(X_train_sc, y_train, test_size=0.2, random_state=42, stratify=y_train)

# TODO 2: itera sobre k_values = [1, 3, 5, 7, 9, 11, 15]
#          guarda acc en train_sub y val para cada k
k_values = [1, 3, 5, 7, 9, 11, 15]
acc_tr_list  = []
acc_val_list = []

for k in k_values:
    knn_temp = KNeighborsClassifier(n_neighbors=k)
    knn_temp.fit(X_tr_sub, y_tr_sub)
    acc_tr_list.append(accuracy_score(y_tr_sub, knn_temp.predict(X_tr_sub)))
    acc_val_list.append(accuracy_score(y_val, knn_temp.predict(X_val)))

# TODO 3: identifica k óptimo (argmax de acc_val_list)
k_optimo = k_values[np.argmax(acc_val_list)]
print(f'k óptimo = {k_optimo}  (val accuracy = {max(acc_val_list):.4f})')

# --- COMPLETA EL CÓDIGO ---
# TODO: grafica train vs val accuracy en función de k
# Incluye: línea vertical en k óptimo, leyenda, títulos, colores UPCH

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(k_values, acc_tr_list, marker='o', label='Train Accuracy', color=UPCH_GRAY)
ax.plot(k_values, acc_val_list, marker='s', label='Val Accuracy', color=UPCH_BLUE)
ax.axvline(x=k_optimo, color=UPCH_RED, linestyle='--', label=f'k óptimo: {k_optimo}')
ax.set_xlabel('Valor de k'); ax.set_ylabel('Accuracy')
ax.set_title('Selección de k para k-NN'); ax.legend()

plt.tight_layout()
plt.savefig('knn_seleccion_k_diabetes.png', dpi=150, bbox_inches='tight')
plt.show()

# --- COMPLETA EL CÓDIGO ---
# TODO: entrena k-NN final con k_optimo sobre TODO X_train_sc
#       predice sobre X_test_sc
knn_opt = KNeighborsClassifier(n_neighbors=k_optimo)
knn_opt.fit(X_train_sc, y_train)
y_pred_knn = knn_opt.predict(X_test_sc)

acc_knn = accuracy_score(y_test, y_pred_knn)
print(f'k-NN (k={k_optimo}) — Accuracy final en test: {acc_knn:.4f}')

"""---
## Ejercicio 7 — Evaluación clínica

### Paso 7.1 — Matrices de confusión lado a lado
"""

# --- COMPLETA EL CÓDIGO ---
# TODO: grafica las dos matrices de confusión lado a lado (fig con 2 subplots)
# Usa ConfusionMatrixDisplay, cmap='Reds', labels=['No diabética', 'Diabética']

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_knn, ax=axes[0], cmap='Reds', display_labels=['No diabética', 'Diabética'])
axes[0].set_title(f'k-NN (k={k_optimo})')
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_gnb, ax=axes[1], cmap='Reds', display_labels=['No diabética', 'Diabética'])
axes[1].set_title('Naive Bayes')

plt.tight_layout()
plt.savefig('cm_comparacion.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Paso 7.2 — Tabla de métricas clínicas"""

# --- COMPLETA EL CÓDIGO ---
# TODO: calcula para ambos modelos: accuracy, precision, recall, f1
#       sobre la clase positiva (Diabética = 1)
#       imprime una tabla comparativa clara

print(f"k-NN -> Accuracy: {accuracy_score(y_test, y_pred_knn):.4f}, Precision: {precision_score(y_test, y_pred_knn):.4f}, Recall: {recall_score(y_test, y_pred_knn):.4f}, F1: {f1_score(y_test, y_pred_knn):.4f}")
print(f"NB   -> Accuracy: {accuracy_score(y_test, y_pred_gnb):.4f}, Precision: {precision_score(y_test, y_pred_gnb):.4f}, Recall: {recall_score(y_test, y_pred_gnb):.4f}, F1: {f1_score(y_test, y_pred_gnb):.4f}")

print('\n→ ¿Cuál modelo tiene mayor Recall? ¿Por qué eso importa clínicamente?')

"""### Paso 7.3 — Gráfico comparativo de métricas"""

# --- COMPLETA EL CÓDIGO ---
# TODO: grafica un bar chart comparando accuracy, precision, recall y F1
# para k-NN y Naive Bayes, con colores UPCH

metricas = ['Accuracy', 'Precision', 'Recall', 'F1']
knn_scores = [accuracy_score(y_test, y_pred_knn), precision_score(y_test, y_pred_knn), recall_score(y_test, y_pred_knn), f1_score(y_test, y_pred_knn)]
gnb_scores = [accuracy_score(y_test, y_pred_gnb), precision_score(y_test, y_pred_gnb), recall_score(y_test, y_pred_gnb), f1_score(y_test, y_pred_gnb)]

x = np.arange(len(metricas))
width = 0.35
fig, ax = plt.subplots(figsize=(8, 5))
ax.bar(x - width/2, knn_scores, width, label='k-NN', color=UPCH_BLUE)
ax.bar(x + width/2, gnb_scores, width, label='Naive Bayes', color=UPCH_RED)
ax.set_xticks(x); ax.set_xticklabels(metricas)
ax.set_title('Comparación de Métricas: k-NN vs Naive Bayes'); ax.legend()

plt.savefig('comparacion_metricas.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## Ejercicio 8 — Umbral de decisión y probabilidades posteriores

Naive Bayes entrega **probabilidades**, no solo etiquetas. En clínica podemos ajustar el umbral de decisión según el contexto:
- Tamizaje masivo → umbral bajo → maximizar recall (menos FN)
- Confirmación diagnóstica → umbral alto → maximizar precision (menos FP)

Por defecto, scikit-learn usa umbral = 0.5.
"""

# Probabilidades posteriores de Naive Bayes
proba_gnb = gnb.predict_proba(X_test_imp)[:, 1]  # P(Diabética | x)

# --- COMPLETA EL CÓDIGO ---
# TODO 1: grafica el histograma de probabilidades P(Diabética | x)
#         diferenciando por clase real (y_test == 0 y y_test == 1)
#         con alpha=0.6, UPCH_BLUE y UPCH_RED
#         agrega una línea vertical en 0.5 (umbral por defecto)

fig, ax = plt.subplots(figsize=(8, 4))
ax.hist(proba_gnb[y_test == 0], bins=20, alpha=0.6, color=UPCH_BLUE, label='Real: No diabética')
ax.hist(proba_gnb[y_test == 1], bins=20, alpha=0.6, color=UPCH_RED, label='Real: Diabética')
ax.axvline(0.5, color='black', linestyle='dashed', linewidth=2, label='Umbral 0.5')
ax.set_title('Distribución de Probabilidades P(Diabética | x) - Naive Bayes')
ax.legend()

plt.tight_layout()
plt.savefig('histograma_proba.png', dpi=150, bbox_inches='tight')
plt.show()

# --- COMPLETA EL CÓDIGO ---
# TODO 2: evalúa el modelo con umbral = 0.35 (tamizaje) y umbral = 0.65 (confirmación)
#         Compara recall y precision en ambos casos vs el umbral por defecto (0.5)
#         Imprime una tabla con: umbral, precision, recall, F1

# Evaluación de umbrales
print(f"{'Umbral':<10} {'Precision':<12} {'Recall':<12} {'F1':<12}")
for umbral in [0.35, 0.50, 0.65]:
    y_pred_umbral = (proba_gnb >= umbral).astype(int)
    print(f"{umbral:<10} {precision_score(y_test, y_pred_umbral):.4f}       {recall_score(y_test, y_pred_umbral):.4f}       {f1_score(y_test, y_pred_umbral):.4f}")
print()
print('→ ¿Para un programa de tamizaje de diabetes en comunidades rurales del Perú,')
print('  qué umbral recomendarías y por qué?')

"""---
## Ejercicio 9 — Impacto del Prior (reflexión bayesiana)

El Teorema de Bayes que estudiamos en Clase 1 está en el corazón de Naive Bayes. Ahora lo aplicamos directamente.
"""

# Naive Bayes con prior ajustado manualmente
# Simulamos que estamos en una población con baja prevalencia de diabetes (5%)

# --- COMPLETA EL CÓDIGO ---
# TODO 1: entrena un GaussianNB con priors=[0.95, 0.05]
#         (usar parámetro priors= en el constructor)
gnb_low_prev = GaussianNB(priors=[0.95, 0.05])
gnb_low_prev.fit(X_train_imp, y_train)

# TODO 2: predice y calcula recall, precision y accuracy en test
y_pred_lp = gnb_low_prev.predict(X_test_imp)

print('Comparación de priors:')
print(f'  Prior original (~35% diabetes):  Recall={recall_score(y_test, y_pred_gnb):.4f}  Precision={precision_score(y_test, y_pred_gnb):.4f}')
print(f'  Prior 5% diabetes:               Recall={recall_score(y_test, y_pred_lp):.4f}  Precision={precision_score(y_test, y_pred_lp):.4f}')
print()
print('📝 Reflexión: ¿Qué le ocurre al recall cuando la prevalencia baja?')
print('   Conecta esto con la Actividad 4 de Clase 1 (Teorema de Bayes).')

"""---
## Ejercicio 10 — Análisis final e interpretación clínica

Responde las siguientes preguntas integrando los resultados obtenidos:

### 10.1 — ¿Cuál modelo elegirías y para qué escenario?

Completa la tabla:

| Escenario | Modelo recomendado | Métrica prioritaria | Justificación |
|---|---|---|---|
| Screening masivo en posta rural | Naive Bayes (umbral 0.35) | Recall | Buscamos no perder a ningún paciente enfermo (minimizar falsos negativos). Bajar el umbral nos da máxima sensibilidad. |
| Confirmación diagnóstica en hospital | k-NN o Naive Bayes (umbral 0.65) | Precisión | Al confirmar la enfermedad, queremos estar muy seguros para evitar tratamientos innecesarios (minimizar falsos positivos). |
| Sistema embebido en glucómetro portátil | Naive Bayes | ___ | Naive Bayes requiere mucha menos memoria y poder computacional, ya que solo guarda medias y varianzas; k-NN requiere guardar todos los datos de entrenamiento en la memoria del dispositivo. |

**📝 Tu respuesta (edita esta celda)**

### 10.2 — Limitaciones del análisis

1. ¿Qué asunciones de Naive Bayes se violan en este dataset? ¿Cómo lo detectaste?
2. ¿Por qué k-NN puede ser problemático si el dataset tuviera 50,000 pacientes y 200 features?
3. ¿Qué otra métrica de evaluación sería importante reportar en el contexto clínico?

**📝 Tu respuesta (edita esta celda):**
1. La suposición de independencia de NB se viola en datos metabólicos. Se detecta con las altas correlaciones del mapa de calor
2. Porque debe calcular la distancia euclidiana entre el paciente nuevo y los 50k registros antes de predecir.
3. El ROC sería bueno para evaluar el balance entre sensibilidad y especificidad independientemente del umbral. O el F2-Score que pondera más al recall que a la precisión
"""

# Resumen ejecutivo final
print('=' * 60)
print('          RESUMEN DEL CHALLENGE 2')
print('=' * 60)
print(f'Dataset: Pima Indians Diabetes  (N={len(df)}, d=8)')
print(f'Prevalencia en test: {100*(y_test==1).mean():.1f}%')
print()
print(f'{"Modelo":<20} {"Accuracy":<12} {"Recall":<12} {"Precision":<12} {"F1"}')
print('-' * 60)

for nombre, y_p in [(f'k-NN (k={k_optimo})', y_pred_knn), ('Naive Bayes', y_pred_gnb)]:
    print(f'{nombre:<20} '
          f'{accuracy_score(y_test, y_p):.4f}       '
          f'{recall_score(y_test, y_p):.4f}       '
          f'{precision_score(y_test, y_p):.4f}       '
          f'{f1_score(y_test, y_p):.4f}')

print()
print('Archivos generados:')
print('  distribucion_diabetes.png   eda_diabetes.png')
print('  knn_seleccion_k_diabetes.png cm_comparacion.png')
print('  comparacion_metricas.png    histograma_proba.png')